/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2018-04-06 19:12:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LogInBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/KonaKart/webapps/konakart/WEB-INF/lib/struts2-core-kk-2.3.8.jar!/META-INF/struts-tags.tld", Long.valueOf(1355759346000L));
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1517397686000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1517397686000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-kk-2.3.8.jar", Long.valueOf(1516953392000L));
    _jspx_dependants.put("/WEB-INF/tiles-jsp.tld", Long.valueOf(1517397686000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");  
      out.write('\r');
      out.write('\n');
 com.konakart.al.CustomerMgr customerMgr = kkEng.getCustomerMgr();
      out.write('\r');
      out.write('\n');
 com.konakart.appif.CustomerIf currentCustomer = customerMgr.getCurrentCustomer();
      out.write('\r');
      out.write('\n');
 boolean allowFacebook = kkEng.getConfigAsBoolean("MODULE_OTHER_FACEBOOK_LOGIN_STATUS",false,false);
      out.write('\r');
      out.write('\n');
 boolean allowGooglePlus = kkEng.getConfigAsBoolean("MODULE_OTHER_GOOGLEPLUS_LOGIN_STATUS",false,false);
      out.write('\r');
      out.write('\n');
 boolean allowPayPal = kkEng.getConfigAsBoolean("MODULE_OTHER_PAYPAL_LOGIN_STATUS",false,false);
      out.write('\r');
      out.write('\n');
 boolean isEE = kkEng.isEnterprise();
      out.write("\r\n");
      out.write("\r\n");
if (allowPayPal) {
      out.write("\r\n");
      out.write("\t<script src='https://www.paypalobjects.com/js/external/api.js'></script>\r\n");
}
      out.write('\r');
      out.write('\n');
if (allowGooglePlus) {
      out.write("\r\n");
      out.write("\t<script src=\"https://apis.google.com/js/client:platform.js?onload=gpStart\" async defer></script>\r\n");
      out.write("\t<meta name=\"google-signin-client_id\" content=\"");
      out.print(kkEng.getConfig("MODULE_OTHER_GOOGLEPLUS_CLIENT_ID"));
      out.write("\">\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("\r\n");
if (allowPayPal) {
      out.write('\r');
      out.write('\n');
      out.write('	');
 boolean useSandbox = kkEng.getConfigAsBoolean("MODULE_OTHER_PAYPAL_LOGIN_RUN_IN_SANDBOX",true,false);
      out.write("\r\n");
      out.write("\tpaypal.use( ['login'], function (login) {\r\n");
      out.write("\t\t  login.render ({\r\n");
      out.write("\t\t    \"appid\":\"");
      out.print(kkEng.getConfig("MODULE_OTHER_PAYPAL_CLIENT_ID"));
      out.write("\",\r\n");
      out.write("\t\t    ");
if (useSandbox) {
      out.write("\r\n");
      out.write("\t\t    \"authend\":\"sandbox\",\r\n");
      out.write("\t\t    ");
}
      out.write("\r\n");
      out.write("\t\t    \"scopes\":\"");
      out.print(kkEng.getConfig("MODULE_OTHER_PAYPAL_LOGIN_SCOPES"));
      out.write("\",\r\n");
      out.write("\t\t    \"containerid\":\"lippButton\",\r\n");
      out.write("\t\t    \"locale\":\"en-us\",\r\n");
      out.write("\t\t    \"returnurl\":\"");
      out.print(kkEng.getConfig("MODULE_OTHER_PAYPAL_LOGIN_RETURN_URL"));
      out.write("\"\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t});\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
if (allowFacebook) {
      out.write("\r\n");
      out.write("  window.fbAsyncInit = function() {\r\n");
      out.write("    FB.init({\r\n");
      out.write("      appId      : '");
      out.print(kkEng.getConfig("MODULE_OTHER_FACEBOOK_APP_ID"));
      out.write("',\r\n");
      out.write("      version    : 'v2.5'\r\n");
      out.write("    });\r\n");
      out.write("    $(\"#fb-button\").css(\"display\",\"inline\");\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  (function(d, s, id){\r\n");
      out.write("     var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("     if (d.getElementById(id)) {return;}\r\n");
      out.write("     js = d.createElement(s); js.id = id;\r\n");
      out.write("     js.src = \"//connect.facebook.net/en_US/sdk.js\";\r\n");
      out.write("     fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("   }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("   \r\n");
      out.write("\tfunction fbKKLogin(response) {\r\n");
      out.write("\t\t$(\"#fb-button\").hide();\r\n");
      out.write("\t\t$(\"#fb-wait\").text('");
      if (_jspx_meth_kk_005fmsg_005f0(_jspx_page_context))
        return;
      out.write("').addClass('fb-loading');\r\n");
      out.write("\t\tdocument.getElementById('loginToken').value = response.authResponse.accessToken;\r\n");
      out.write("\t\tdocument.getElementById('loginType').value = \"");
      out.print(com.konakart.al.CustomerMgr.FACEBOOK);
      out.write("\";\r\n");
      out.write("        fbGetEmail();\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fbGetEmail() {\r\n");
      out.write("\t   FB.api('/me?fields=email', function(response) {\r\n");
      out.write("\t   \tif (response.email == null || response.email.length == 0) {\r\n");
      out.write("\t   \t\tdocument.getElementById('social-status').innerHTML = '");
      if (_jspx_meth_kk_005fmsg_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t   \t\t$(\"#fb-wait\").text('').removeClass('fb-loading');\r\n");
      out.write("\t   \t\t$(\"#fb-button\").show();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.getElementById('extLoginForm').submit();\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t   });\r\n");
      out.write("\t};\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
if (allowGooglePlus) {
      out.write("\r\n");
      out.write("\tfunction gpStart() {\r\n");
      out.write("\t\t  gapi.load('auth2', function() {\r\n");
      out.write("\t\t    gapi.client.load('plus','v1').then(function() {\r\n");
      out.write("\t\t    \t$(\"#gp-button\").css(\"display\",\"inline\");\r\n");
      out.write(" \t\t      });\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar gpUpdate = function(authResult) {\r\n");
      out.write("\t\t if (authResult.isSignedIn.get()) {\r\n");
      out.write("\t\t \tvar user = authResult.currentUser.get();\r\n");
      out.write("\t\t   \tif (user.getBasicProfile().getEmail() == null || user.getBasicProfile().getEmail().length == 0) {\r\n");
      out.write("\t\t   \t\tdocument.getElementById('social-status').innerHTML = '");
      if (_jspx_meth_kk_005fmsg_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t   \t\treturn;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t$(\"#gp-button\").hide();\r\n");
      out.write("\t\t\t$(\"#gp-wait\").text('");
      if (_jspx_meth_kk_005fmsg_005f3(_jspx_page_context))
        return;
      out.write("').addClass('gp-loading');\r\n");
      out.write("\t\t\tdocument.getElementById('loginToken').value = user.getAuthResponse().id_token;\r\n");
      out.write("\t\t\tdocument.getElementById('loginType').value = \"");
      out.print(com.konakart.al.CustomerMgr.GOOGLEPLUS);
      out.write("\";\r\n");
      out.write("\t\t\tdocument.getElementById('extLoginForm').submit();\r\n");
      out.write("\t\t } else if (authResult['error'] ||\r\n");
      out.write("\t\t\tauthResult.currentUser.get().getAuthResponse() == null) {\r\n");
      out.write("\t\t\tdocument.getElementById('social-status').innerHTML = '");
      if (_jspx_meth_kk_005fmsg_005f4(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t } else  {\r\n");
      out.write("\t\t\t authResult.isSignedIn.listen(gpListener);\r\n");
      out.write("\t\t\t authResult.signIn({\r\n");
      out.write("\t\t\t\t  'scope': 'profile email'\r\n");
      out.write("\t\t\t });\t\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar gpListener = function(loggedIn) {\t\t\r\n");
      out.write("\t\tif (loggedIn == true) {\r\n");
      out.write("\t\t\tgpUpdate(gapi.auth2.getAuthInstance());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\t$(\"#password\").keydown(function (e){\r\n");
      out.write("\t\t    if(e.keyCode == 13){\r\n");
      out.write("\t\t    \tformValidate('form1', 'continue-button');\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t");
if (allowGooglePlus) {
      out.write("\r\n");
      out.write("\t\t$(\"#gp-button\").click(function() {\r\n");
      out.write("\t\t\tvar authResult = gapi.auth2.getAuthInstance();\r\n");
      out.write("\t\t\tif (authResult == null) {\r\n");
      out.write("\t\t\t      gapi.auth2.init({fetch_basic_profile: true,\r\n");
      out.write("\t\t\t          scope:'https://www.googleapis.com/auth/plus.login'}).then(\r\n");
      out.write("\t\t\t            function (){\r\n");
      out.write("\t\t\t            \tauthResult = gapi.auth2.getAuthInstance();\r\n");
      out.write("\t\t\t            \tgpUpdate(authResult);\r\n");
      out.write("\t\t\t            });\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("            \tgpUpdate(authResult);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t");
}
      out.write('\r');
      out.write('\n');
      out.write('	');
if (allowFacebook) {
      out.write("\r\n");
      out.write("\t\t$(\"#fb-button\").click(function() {\r\n");
      out.write("\t\t\tFB.getLoginStatus(function(response) {\r\n");
      out.write("\t\t\t    if (response==null || response.authResponse == 'undefined' || response.status!='connected') {\r\n");
      out.write("\t\t\t    \tFB.login(function(response){\r\n");
      out.write("\t\t\t\t     \tif (response.status === 'connected') {\r\n");
      out.write("\t\t\t\t     \t\tfbKKLogin(response);\r\n");
      out.write("\t\t\t\t       \t} else if (response.status === 'not_authorized') {\r\n");
      out.write("\t\t\t\t         \tdocument.getElementById('social-status').innerHTML = '");
      if (_jspx_meth_kk_005fmsg_005f5(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\t\t       \t} else {\r\n");
      out.write("\t\t\t\t         \tdocument.getElementById('social-status').innerHTML = '");
      if (_jspx_meth_kk_005fmsg_005f6(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\t\t       \t}    \r\n");
      out.write("\t\t\t    \t}, {scope: 'email'});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tfbKKLogin(response);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t");
}
      out.write("\t\t\t \r\n");
      out.write("});\t\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
if (allowPayPal) {
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.LIwPP { height: 27px !important;} \r\n");
      out.write("\t</style>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
if (allowFacebook || allowGooglePlus) {
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"LoginSubmit.action\" id='extLoginForm' method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t\t\t<input id=\"loginToken\" name=\"loginToken\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t\t<input id=\"loginType\" name=\"loginType\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t");
if (allowFacebook || allowGooglePlus || allowPayPal) {
      out.write(" \r\n");
      out.write("\t\t\t\t<h1 id=\"page-title\">");
      if (_jspx_meth_kk_005fmsg_005f7(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("    \t\t\t<div class=\"content-area rounded-corners\">\r\n");
      out.write("\t\t\t\t\t<div id=\"social-status\" class=\"messageStackError\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");
if (allowFacebook) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"fb-button\" style=\"display: none\";><img src=\"");
      out.print(kkEng.getImageBase());
      out.write("/btn_facebook_login.png\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"fb-wait\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if (allowGooglePlus) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"gp-button\" style=\"display: none\"><img src=\"");
      out.print(kkEng.getImageBase());
      out.write("/btn_googleplus_login.png\"></div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"gp-wait\"></div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if (allowPayPal) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id='lippButton'></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
if (customerMgr.getLoginType() != null 
							&& (customerMgr.getLoginType().equals(com.konakart.al.CustomerMgr.FACEBOOK) 
									|| customerMgr.getLoginType().equals(com.konakart.al.CustomerMgr.GOOGLEPLUS) 
									|| customerMgr.getLoginType().equals(com.konakart.al.CustomerMgr.PAYPAL))) {
      out.write(" \t    \t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_s_005fif_005f1(_jspx_page_context))
        return;
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t<h1 id=\"page-title\">");
      if (_jspx_meth_kk_005fmsg_005f8(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write(" \t    \t\t<div id=\"new-account-area\" class=\"content-area rounded-corners\">\r\n");
      out.write("\t\t\t\t\t");
if (customerMgr.getLoginType() == null) {
      out.write(" \t    \t\t\r\n");
      out.write("\t\t\t\t\t    ");
      if (_jspx_meth_s_005fif_005f2(_jspx_page_context))
        return;
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_s_005fif_005f3(_jspx_page_context))
        return;
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t    \t\t<div class=\"sign-in-column-left\">\r\n");
      out.write("\t\t\t    \t\t<form action=\"LoginSubmit.action\" id=\"form1\" method=\"post\"> \r\n");
      out.write("\t\t\t    \t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" name=\"xsrf_token\"/>\r\n");
      out.write("\t\t\t    \t\t\t<div class=\"form-section\">\r\n");
      out.write("\t\t    \t\t\t\t<h3>");
      if (_jspx_meth_kk_005fmsg_005f9(_jspx_page_context))
        return;
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if (isEE) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>");
      if (_jspx_meth_kk_005fmsg_005f10(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>");
      if (_jspx_meth_kk_005fmsg_005f11(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"loginUsername\" name=\"loginUsername\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"validation-msg\"></span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>");
      if (_jspx_meth_kk_005fmsg_005f12(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"validation-msg\"></span>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign-in-button-container\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a onclick=\"javascript:formValidate('form1', 'continue-button');\" id=\"continue-button\" class=\"button small-rounded-corners\"><span>");
      if (_jspx_meth_kk_005fmsg_005f13(_jspx_page_context))
        return;
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"ForgotPassword.action\" class=\"text-link\" id=\"forgot-password-link\">");
      if (_jspx_meth_kk_005fmsg_005f14(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"sign-in-column-right centered\">\r\n");
      out.write("\t\t\t\t\t\t<h3>");
      if (_jspx_meth_kk_005fmsg_005f15(_jspx_page_context))
        return;
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"CustomerRegistration.action?forceReg=true\" class=\"button small-rounded-corners\"><span>");
      if (_jspx_meth_kk_005fmsg_005f16(_jspx_page_context))
        return;
      out.write("</span></a>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t");
if (kkEng.getConfigAsBoolean("ALLOW_CHECKOUT_WITHOUT_REGISTRATION",false)) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"CustomerRegistration.action\" class=\"button small-rounded-corners\"><span>");
      if (_jspx_meth_kk_005fmsg_005f17(_jspx_page_context))
        return;
      out.write("</span></a>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_kk_005fmsg_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f0 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f0_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f0.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f0.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(74,22) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f0.setKey("login.body.fb.processing");
      int _jspx_eval_kk_005fmsg_005f0 = _jspx_th_kk_005fmsg_005f0.doStartTag();
      if (_jspx_th_kk_005fmsg_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f0);
      _jspx_th_kk_005fmsg_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f0, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f1 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f1_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f1.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f1.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(84,60) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f1.setKey("login.body.fb.no.email");
      int _jspx_eval_kk_005fmsg_005f1 = _jspx_th_kk_005fmsg_005f1.doStartTag();
      if (_jspx_th_kk_005fmsg_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f1);
      _jspx_th_kk_005fmsg_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f1, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f2 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f2_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f2.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f2.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(107,61) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f2.setKey("login.body.gp.no.email");
      int _jspx_eval_kk_005fmsg_005f2 = _jspx_th_kk_005fmsg_005f2.doStartTag();
      if (_jspx_th_kk_005fmsg_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f2);
      _jspx_th_kk_005fmsg_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f2, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f3 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f3_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f3.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f3.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(111,23) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f3.setKey("login.body.gp.processing");
      int _jspx_eval_kk_005fmsg_005f3 = _jspx_th_kk_005fmsg_005f3.doStartTag();
      if (_jspx_th_kk_005fmsg_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f3);
      _jspx_th_kk_005fmsg_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f3, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f4 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f4_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f4.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f4.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(117,57) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f4.setKey("login.body.gp.no.auth");
      int _jspx_eval_kk_005fmsg_005f4 = _jspx_th_kk_005fmsg_005f4.doStartTag();
      if (_jspx_th_kk_005fmsg_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f4);
      _jspx_th_kk_005fmsg_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f4, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f5 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f5_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f5.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f5.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(164,68) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f5.setKey("login.body.fb.no.auth");
      int _jspx_eval_kk_005fmsg_005f5 = _jspx_th_kk_005fmsg_005f5.doStartTag();
      if (_jspx_th_kk_005fmsg_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f5);
      _jspx_th_kk_005fmsg_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f5, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f6 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f6_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f6.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f6.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(166,68) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f6.setKey("login.body.fb.no.auth");
      int _jspx_eval_kk_005fmsg_005f6 = _jspx_th_kk_005fmsg_005f6.doStartTag();
      if (_jspx_th_kk_005fmsg_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f6);
      _jspx_th_kk_005fmsg_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f6, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f7 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f7_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f7.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f7.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(193,24) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f7.setKey("login.body.use.social.network");
      int _jspx_eval_kk_005fmsg_005f7 = _jspx_th_kk_005fmsg_005f7.doStartTag();
      if (_jspx_th_kk_005fmsg_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f7);
      _jspx_th_kk_005fmsg_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f7, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(222,7) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("hasActionErrors()");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t   <div class=\"messageStackError\">  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_s_005fiterator_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t\t\t</div>  \r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    boolean _jspx_th_s_005fiterator_005f0_reused = false;
    try {
      _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      // /WEB-INF/jsp/LogInBody.jsp(224,9) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f0.setValue("actionErrors");
      int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fiterator_005f0);
        }
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f0);
      _jspx_th_s_005fiterator_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fiterator_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fiterator_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f0_reused = false;
    try {
      _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
      // /WEB-INF/jsp/LogInBody.jsp(225,10) name = escape type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f0.setEscape(false);
      int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
      if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      _jspx_th_s_005fproperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f1_reused = false;
    try {
      _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(229,7) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f1.setTest("hasActionMessages()");
      int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f1);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t   <div class=\"messageStackSuccess\">  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_s_005fiterator_005f1(_jspx_th_s_005fif_005f1, _jspx_page_context))
            return true;
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t\t\t</div>  \r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      _jspx_th_s_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f1 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    boolean _jspx_th_s_005fiterator_005f1_reused = false;
    try {
      _jspx_th_s_005fiterator_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f1);
      // /WEB-INF/jsp/LogInBody.jsp(231,9) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f1.setValue("actionMessages");
      int _jspx_eval_s_005fiterator_005f1 = _jspx_th_s_005fiterator_005f1.doStartTag();
      if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fiterator_005f1);
        }
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fiterator_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f1);
      _jspx_th_s_005fiterator_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fiterator_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fiterator_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f1_reused = false;
    try {
      _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f1);
      // /WEB-INF/jsp/LogInBody.jsp(232,10) name = escape type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f1.setEscape(false);
      int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
      if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      _jspx_th_s_005fproperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f8 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f8_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f8.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f8.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(240,23) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f8.setKey("login.body.sign.in");
      int _jspx_eval_kk_005fmsg_005f8 = _jspx_th_kk_005fmsg_005f8.doStartTag();
      if (_jspx_th_kk_005fmsg_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f8);
      _jspx_th_kk_005fmsg_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f8, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f2 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f2_reused = false;
    try {
      _jspx_th_s_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(243,9) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f2.setTest("hasActionErrors()");
      int _jspx_eval_s_005fif_005f2 = _jspx_th_s_005fif_005f2.doStartTag();
      if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f2);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t   <div class=\"messageStackError\">  \r\n");
          out.write("\t\t\t\t\t\t        ");
          if (_jspx_meth_s_005fiterator_005f2(_jspx_th_s_005fif_005f2, _jspx_page_context))
            return true;
          out.write("  \r\n");
          out.write("\t\t\t    \t\t\t</div>  \r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f2);
      _jspx_th_s_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f2 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    boolean _jspx_th_s_005fiterator_005f2_reused = false;
    try {
      _jspx_th_s_005fiterator_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f2);
      // /WEB-INF/jsp/LogInBody.jsp(245,14) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f2.setValue("actionErrors");
      int _jspx_eval_s_005fiterator_005f2 = _jspx_th_s_005fiterator_005f2.doStartTag();
      if (_jspx_eval_s_005fiterator_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fiterator_005f2);
        }
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t            ");
          if (_jspx_meth_s_005fproperty_005f2(_jspx_th_s_005fiterator_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f2);
      _jspx_th_s_005fiterator_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fiterator_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fiterator_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f2_reused = false;
    try {
      _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f2);
      // /WEB-INF/jsp/LogInBody.jsp(246,18) name = escape type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f2.setEscape(false);
      int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
      if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      _jspx_th_s_005fproperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f3 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f3_reused = false;
    try {
      _jspx_th_s_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f3.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(250,6) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f3.setTest("hasActionMessages()");
      int _jspx_eval_s_005fif_005f3 = _jspx_th_s_005fif_005f3.doStartTag();
      if (_jspx_eval_s_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f3);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t   <div class=\"messageStackSuccess\">  \r\n");
          out.write("\t\t\t\t\t\t        ");
          if (_jspx_meth_s_005fiterator_005f3(_jspx_th_s_005fif_005f3, _jspx_page_context))
            return true;
          out.write("  \r\n");
          out.write("\t\t\t    \t\t\t</div>  \r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_s_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f3);
      _jspx_th_s_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f3 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    boolean _jspx_th_s_005fiterator_005f3_reused = false;
    try {
      _jspx_th_s_005fiterator_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fiterator_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f3);
      // /WEB-INF/jsp/LogInBody.jsp(252,14) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fiterator_005f3.setValue("actionMessages");
      int _jspx_eval_s_005fiterator_005f3 = _jspx_th_s_005fiterator_005f3.doStartTag();
      if (_jspx_eval_s_005fiterator_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fiterator_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fiterator_005f3);
        }
        do {
          out.write("  \r\n");
          out.write("\t\t\t\t\t\t            ");
          if (_jspx_meth_s_005fproperty_005f3(_jspx_th_s_005fiterator_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_s_005fiterator_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fiterator_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fiterator_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f3);
      _jspx_th_s_005fiterator_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fiterator_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fiterator_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    boolean _jspx_th_s_005fproperty_005f3_reused = false;
    try {
      _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f3);
      // /WEB-INF/jsp/LogInBody.jsp(253,18) name = escape type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fproperty_005f3.setEscape(false);
      int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
      if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      _jspx_th_s_005fproperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fproperty_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fproperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f9 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f9_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f9.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f9.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(262,14) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f9.setKey("login.body.returning.customer");
      int _jspx_eval_kk_005fmsg_005f9 = _jspx_th_kk_005fmsg_005f9.doStartTag();
      if (_jspx_th_kk_005fmsg_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f9);
      _jspx_th_kk_005fmsg_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f9, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f10 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f10_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f10.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f10.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(265,17) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f10.setKey("login.body.email.username");
      int _jspx_eval_kk_005fmsg_005f10 = _jspx_th_kk_005fmsg_005f10.doStartTag();
      if (_jspx_th_kk_005fmsg_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f10);
      _jspx_th_kk_005fmsg_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f10, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f11 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f11_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f11.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f11.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(267,17) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f11.setKey("login.body.email");
      int _jspx_eval_kk_005fmsg_005f11 = _jspx_th_kk_005fmsg_005f11.doStartTag();
      if (_jspx_th_kk_005fmsg_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f11);
      _jspx_th_kk_005fmsg_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f11, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f12 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f12_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f12.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f12.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(273,16) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f12.setKey("login.body.password");
      int _jspx_eval_kk_005fmsg_005f12 = _jspx_th_kk_005fmsg_005f12.doStartTag();
      if (_jspx_th_kk_005fmsg_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f12);
      _jspx_th_kk_005fmsg_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f12, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f13 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f13_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f13.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f13.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(278,139) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f13.setKey("login.body.sign.in");
      int _jspx_eval_kk_005fmsg_005f13 = _jspx_th_kk_005fmsg_005f13.doStartTag();
      if (_jspx_th_kk_005fmsg_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f13);
      _jspx_th_kk_005fmsg_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f13, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f14 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f14_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f14.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f14.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(279,85) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f14.setKey("login.body.forgotten.password");
      int _jspx_eval_kk_005fmsg_005f14 = _jspx_th_kk_005fmsg_005f14.doStartTag();
      if (_jspx_th_kk_005fmsg_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f14);
      _jspx_th_kk_005fmsg_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f14, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f15 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f15_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f15.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f15.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(285,10) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f15.setKey("login.body.new.customer");
      int _jspx_eval_kk_005fmsg_005f15 = _jspx_th_kk_005fmsg_005f15.doStartTag();
      if (_jspx_th_kk_005fmsg_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f15);
      _jspx_th_kk_005fmsg_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f15, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f16 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f16_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f16.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f16.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(287,102) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f16.setKey("login.body.register");
      int _jspx_eval_kk_005fmsg_005f16 = _jspx_th_kk_005fmsg_005f16.doStartTag();
      if (_jspx_th_kk_005fmsg_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f16);
      _jspx_th_kk_005fmsg_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f16, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_kk_005fmsg_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  kk:msg
    com.konakart.kktags.MsgTag _jspx_th_kk_005fmsg_005f17 = (com.konakart.kktags.MsgTag) _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.get(com.konakart.kktags.MsgTag.class);
    boolean _jspx_th_kk_005fmsg_005f17_reused = false;
    try {
      _jspx_th_kk_005fmsg_005f17.setPageContext(_jspx_page_context);
      _jspx_th_kk_005fmsg_005f17.setParent(null);
      // /WEB-INF/jsp/LogInBody.jsp(291,88) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_kk_005fmsg_005f17.setKey("login.body.checkout");
      int _jspx_eval_kk_005fmsg_005f17 = _jspx_th_kk_005fmsg_005f17.doStartTag();
      if (_jspx_th_kk_005fmsg_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fkk_005fmsg_0026_005fkey_005fnobody.reuse(_jspx_th_kk_005fmsg_005f17);
      _jspx_th_kk_005fmsg_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_kk_005fmsg_005f17, _jsp_getInstanceManager(), _jspx_th_kk_005fmsg_005f17_reused);
    }
    return false;
  }
}
